### PR TITLE
Use Composer 2

### PR DESCRIPTION
**Pull request by Crell**

### CODE REVIEW

**Review by bmack — APPROVED** [review]
Thanks for the change!

**Comment by chadwcarlson** [comment]
```
    W: Generating optimized autoload files
    Generating class alias map file
    W: > typo3cms install:fixfolderstructure
    W: sh: 1: typo3cms: not found
    W: Script typo3cms install:fixfolderstructure handling the typo3-cms-scripts event returned with error code 127
    W: Script @typo3-cms-scripts was called via post-autoload-dump
  
  E: Error building project: `composer` could not be run.
```

**Comment by Crell** [comment]
Hm, that doesn't look like a composer-related error?  I runs for me locally.  Sounds more like a path issue.  

This is from the `composer.json` file:

```json
"scripts":{
		"typo3-cms-scripts": [
			"typo3cms install:fixfolderstructure",
			"typo3cms install:generatepackagestates"
		],
		"post-autoload-dump": [
			"@typo3-cms-scripts"
		]
	},
```

But I don't have `typo3cms` in my path, yet it runs for me locally without error.  That's... odd.  @bmack, any theories?

**Comment by chadwcarlson** [comment]
https://github.com/platformsh-templates/typo3/security/dependabot

**Comment by chadwcarlson** [comment]
@RudyWeber see https://pr-16-qp74jfa-rxzar6f4jsbsi.eu-3.platformsh.site/

**Review by RudyWeber — APPROVED** [review]

**Pull request merged**
